owner: SolarNetworkFoundation
repo: upptime

sites:
  - name: SolarQuery
    url: $SOLARQUERY_URL
    __dangerous__body_degraded_if_text_missing: '"allGood":true'
    headers:
      - "Accept": application/json

status-website:
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SolarNetwork Status
  introTitle: "This site tracks system uptime statistics for SolarNetwork services hosted by SolarNetwork Foundation."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/SolarNetworkFoundation/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
